package io.github.miklires.mcodes;

import org.h2.Driver;
import java.nio.file.Path;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

public final class CodeRepository implements AutoCloseable {
    private final String url;
    private final ExecutorService executor=Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mcodes-db-",0).factory());
    public CodeRepository(Path file){this("jdbc:h2:"+file.toAbsolutePath()+";AUTO_SERVER=TRUE");}
    CodeRepository(String url){this.url=url;}
    public CompletableFuture<Void> initialize(){return run(()->{try(Connection c=open();Statement s=c.createStatement()){
        s.executeUpdate("CREATE TABLE IF NOT EXISTS codes(code VARCHAR(32) PRIMARY KEY,type VARCHAR(16) NOT NULL,owner UUID,max_uses INT NOT NULL,per_player INT NOT NULL,expires_at TIMESTAMP WITH TIME ZONE,redeemer_commands VARCHAR(4000) NOT NULL,owner_commands VARCHAR(4000) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,uses INT NOT NULL DEFAULT 0)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS redemptions(tx UUID PRIMARY KEY,code VARCHAR(32) NOT NULL,player UUID NOT NULL,player_name VARCHAR(32) NOT NULL,identity_hash VARCHAR(128),created_at TIMESTAMP WITH TIME ZONE NOT NULL,delivered BOOLEAN NOT NULL DEFAULT FALSE)");}});}
    public CompletableFuture<Boolean> create(CodeDefinition d){return supply(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("INSERT INTO codes VALUES(?,?,?,?,?,?,?,?,TRUE,0)")){p.setString(1,d.code());p.setString(2,d.type().name());p.setObject(3,d.owner());p.setInt(4,d.maxUses());p.setInt(5,d.perPlayer());p.setObject(6,d.expiresAt());p.setString(7,String.join("\n",d.redeemerCommands()));p.setString(8,String.join("\n",d.ownerCommands()));return p.executeUpdate()==1;}catch(SQLException e){if("23505".equals(e.getSQLState()))return false;throw e;}});}
    public CompletableFuture<Boolean> disable(String raw){return supply(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("UPDATE codes SET enabled=FALSE WHERE code=?")){p.setString(1,CodeDefinition.normalize(raw));return p.executeUpdate()==1;}});}
    public CompletableFuture<List<String>> list(){return supply(()->{List<String> out=new ArrayList<>();try(Connection c=open();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT code,type,uses,max_uses,enabled FROM codes ORDER BY code")){while(r.next())out.add(r.getString(1)+" ["+r.getString(2)+"] "+r.getInt(3)+"/"+(r.getInt(4)==0?"∞":r.getInt(4))+(r.getBoolean(5)?"":" disabled"));}return List.copyOf(out);});}
    public CompletableFuture<RedemptionResult> redeem(String raw,UUID player,String name,String identityHash){return supply(()->{String code=CodeDefinition.normalize(raw);try(Connection c=open()){c.setAutoCommit(false);try{CodeDefinition d;int uses;try(PreparedStatement p=c.prepareStatement("SELECT * FROM codes WHERE code=? FOR UPDATE")){p.setString(1,code);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.NOT_FOUND);}d=map(r);uses=r.getInt("uses");if(!r.getBoolean("enabled")||(d.expiresAt()!=null&&d.expiresAt().isBefore(Instant.now()))){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.EXPIRED);}}}if(d.owner()!=null&&d.owner().equals(player)){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.SELF_REFERRAL);}if(d.maxUses()>0&&uses>=d.maxUses()){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.LIMIT_REACHED);}if(count(c,"SELECT COUNT(*) FROM redemptions WHERE code=? AND player=?",code,player)>=d.perPlayer()){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.ALREADY_USED);}if(d.type()==CodeType.REFERRAL&&count(c,"SELECT COUNT(*) FROM redemptions x JOIN codes c ON c.code=x.code WHERE c.type='REFERRAL' AND x.player=?",player)>0){c.rollback();return RedemptionResult.rejected(RedemptionResult.Status.ALREADY_USED);}UUID tx=UUID.randomUUID();try(PreparedStatement p=c.prepareStatement("INSERT INTO redemptions VALUES(?,?,?,?,?,?,FALSE)")){p.setObject(1,tx);p.setString(2,code);p.setObject(3,player);p.setString(4,name);p.setString(5,identityHash);p.setObject(6,Instant.now());p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE codes SET uses=uses+1 WHERE code=?")){p.setString(1,code);p.executeUpdate();}c.commit();return new RedemptionResult(RedemptionResult.Status.ACCEPTED,tx,d);}catch(Throwable e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}});}
    public CompletableFuture<List<PendingReward>> pending(){return supply(()->{List<PendingReward> out=new ArrayList<>();try(Connection c=open();PreparedStatement p=c.prepareStatement("SELECT r.*,c.redeemer_commands,c.owner_commands,c.owner FROM redemptions r JOIN codes c ON c.code=r.code WHERE r.delivered=FALSE ORDER BY r.created_at");ResultSet r=p.executeQuery()){while(r.next())out.add(new PendingReward(r.getObject("tx",UUID.class),r.getObject("player",UUID.class),r.getString("player_name"),r.getObject("owner",UUID.class),lines(r.getString("redeemer_commands")),lines(r.getString("owner_commands"))));}return List.copyOf(out);});}
    public CompletableFuture<Boolean> delivered(UUID tx){return supply(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("UPDATE redemptions SET delivered=TRUE WHERE tx=? AND delivered=FALSE")){p.setObject(1,tx);return p.executeUpdate()==1;}});}
    private static long count(Connection c,String sql,Object...args)throws SQLException{try(PreparedStatement p=c.prepareStatement(sql)){for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);try(ResultSet r=p.executeQuery()){r.next();return r.getLong(1);}}}
    private static CodeDefinition map(ResultSet r)throws SQLException{OffsetDateTime expiry=r.getObject("expires_at",OffsetDateTime.class);return new CodeDefinition(r.getString("code"),CodeType.valueOf(r.getString("type")),r.getObject("owner",UUID.class),r.getInt("max_uses"),r.getInt("per_player"),expiry==null?null:expiry.toInstant(),lines(r.getString("redeemer_commands")),lines(r.getString("owner_commands")));}
    private static List<String> lines(String value){return value==null||value.isBlank()?List.of():List.of(value.split("\n"));}
    private Connection open()throws SQLException{Properties p=new Properties();p.setProperty("user","sa");p.setProperty("password","");return new Driver().connect(url,p);}
    private<T>CompletableFuture<T>supply(SqlSupplier<T> task){return CompletableFuture.supplyAsync(()->{try{return task.get();}catch(Exception e){throw new CompletionException(e);}},executor);}
    private CompletableFuture<Void>run(SqlRunnable task){return supply(()->{task.run();return null;});}
    @Override public void close(){executor.shutdown();}
    @FunctionalInterface private interface SqlSupplier<T>{T get()throws Exception;}@FunctionalInterface private interface SqlRunnable{void run()throws Exception;}
    public record PendingReward(UUID tx,UUID player,String playerName,UUID owner,List<String>playerCommands,List<String>ownerCommands){}
}
