package io.github.miklires.mcodes;

import org.bstats.bukkit.Metrics;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.plugin.java.JavaPlugin;
import java.security.SecureRandom;import java.time.Instant;import java.util.*;

public final class MCodesPlugin extends JavaPlugin implements CommandExecutor,TabCompleter {
    private CodeRepository repository;private IdentityHasher hasher;private volatile boolean ready;
    @Override public void onEnable(){saveDefaultConfig();validateConfig();hasher=new IdentityHasher(getConfig().getString("security.identity-secret"));repository=new CodeRepository(getDataFolder().toPath().resolve("codes"));repository.initialize().thenRun(()->{ready=true;if(getConfig().getBoolean("recovery.auto-retry-pending",true))retryPending();getLogger().info("mCodes "+getPluginMeta().getVersion()+" is ready");}).exceptionally(error->{getLogger().severe("Storage failed: "+root(error).getMessage());sync(()->getServer().getPluginManager().disablePlugin(this));return null;});for(String name:List.of("code","refer")){PluginCommand command=Objects.requireNonNull(getCommand(name));command.setExecutor(this);command.setTabCompleter(this);}if(getConfig().getBoolean("metrics.enabled",true)){int id=Math.max(0,getConfig().getInt("metrics.bstats-id",27942));if(id>0)new Metrics(this,id);}}
    @Override public void onDisable(){ready=false;if(repository!=null)repository.close();}
    private void validateConfig(){getConfig().options().copyDefaults(true);String language=getConfig().getString("language","en_US");if(!Set.of("en_US","ru_RU").contains(language))getConfig().set("language","en_US");String secret=getConfig().getString("security.identity-secret","");if(secret==null||secret.length()<32){byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);getConfig().set("security.identity-secret",HexFormat.of().formatHex(bytes));}getConfig().set("config-version",2);saveConfig();}

    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!ready){message(sender,"§cStorage is still starting.","§cХранилище ещё запускается.");return true;}if(command.getName().equals("refer"))return refer(sender,args);if(args.length==0){usage(sender);return true;}switch(args[0].toLowerCase(Locale.ROOT)){
        case"redeem"->{if(!(sender instanceof Player player)||args.length!=2){usage(sender);return true;}if(!player.hasPermission("mcodes.use")){deny(player);return true;}redeem(player,args[1]);}
        case"list"->{if(!admin(sender))return true;repository.list().thenAccept(lines->respond(sender,()->sender.sendMessage(lines.isEmpty()?text("§7There are no codes.","§7Кодов нет."):String.join("\n",lines))));}
        case"info"->{if(!admin(sender)||args.length!=2){usage(sender);return true;}repository.definition(args[1]).thenAccept(found->respond(sender,()->sender.sendMessage(found.map(this::describe).orElse(text("§cCode not found.","§cКод не найден.")))));}
        case"create"->create(sender,args);
        case"disable","delete","enable"->{if(!admin(sender)||args.length!=2){usage(sender);return true;}boolean enabled=args[0].equalsIgnoreCase("enable");repository.setEnabled(args[1],enabled).thenAccept(ok->respond(sender,()->message(sender,ok?(enabled?"§aCode enabled.":"§aCode disabled."):"§cCode not found.",ok?(enabled?"§aКод включён.":"§aКод отключён."):"§cКод не найден.")));}
        case"pending"->{if(!admin(sender))return true;repository.unresolved().thenAccept(lines->respond(sender,()->sender.sendMessage(lines.isEmpty()?text("§aNo unresolved rewards.","§aНезавершённых наград нет."):String.join("\n",lines))));}
        case"retry"->{if(!admin(sender)||args.length!=2){usage(sender);return true;}try{deliver(UUID.fromString(args[1]),sender);}catch(IllegalArgumentException e){message(sender,"§cInvalid transaction UUID.","§cНекорректный UUID транзакции.");}}
        case"resolve"->{if(!admin(sender)||args.length!=2){usage(sender);return true;}try{repository.delivered(UUID.fromString(args[1])).thenAccept(ok->respond(sender,()->message(sender,ok?"§aTransaction resolved.":"§cTransaction is not claimed.",ok?"§aТранзакция закрыта.":"§cТранзакция не находится в выдаче.")));}catch(IllegalArgumentException e){message(sender,"§cInvalid transaction UUID.","§cНекорректный UUID транзакции.");}}
        case"reload"->{if(!admin(sender))return true;reloadConfig();validateConfig();hasher=new IdentityHasher(getConfig().getString("security.identity-secret"));message(sender,"§aConfiguration reloaded.","§aКонфигурация перезагружена.");}
        default->usage(sender);}return true;}
    private void create(CommandSender sender,String[] args){if(!admin(sender)||args.length<3||args.length>7){usage(sender);return;}try{int limit=parse(args[2],0,1_000_000_000);int perPlayer=args.length>=4?parse(args[3],1,1000):1;long expiresIn=args.length>=5?parse(args[4],0,87600):0;String permission=args.length>=6&&!args[5].equals("-")?args[5]:"";long startsIn=args.length>=7?parse(args[6],0,87600):0;Instant now=Instant.now();Instant startsAt=startsIn==0?null:now.plusSeconds(startsIn*3600);Instant expiresAt=expiresIn==0?null:now.plusSeconds(expiresIn*3600);int perIdentity=Math.clamp(getConfig().getInt("anti-abuse.promo-per-identity",0),0,1000);var definition=new CodeDefinition(args[1],CodeType.PROMO,null,limit,perPlayer,perIdentity,startsAt,expiresAt,permission,Math.clamp(getConfig().getLong("requirements.promo-minimum-playtime-seconds",0),0,315_360_000),getConfig().getStringList("rewards.promo.commands"),List.of());repository.create(definition).thenAccept(ok->respond(sender,()->message(sender,ok?"§aCode created.":"§cThat code already exists.",ok?"§aКод создан.":"§cТакой код уже существует.")));}catch(RuntimeException e){message(sender,"§cInvalid code options: §f"+e.getMessage(),"§cНекорректные параметры кода: §f"+e.getMessage());}}
    private boolean refer(CommandSender sender,String[] args){if(!(sender instanceof Player player)){message(sender,"§cThis command is only available to players.","§cКоманда только для игроков.");return true;}if(!player.hasPermission("mcodes.use")){deny(player);return true;}if(args.length>0){redeem(player,args[0]);return true;}String code=CodeDefinition.normalize(player.getName());String identity=identity(player);var definition=new CodeDefinition(code,CodeType.REFERRAL,player.getUniqueId(),0,1,Math.clamp(getConfig().getInt("anti-abuse.referral-per-identity",1),0,1000),null,null,"",Math.clamp(getConfig().getLong("requirements.referral-minimum-playtime-seconds",3600),0,315_360_000),getConfig().getStringList("rewards.referral.redeemer-commands"),getConfig().getStringList("rewards.referral.owner-commands"));repository.rememberIdentity(player.getUniqueId(),identity).thenCompose(ignored->repository.create(definition)).thenAccept(ignored->respond(player,()->message(player,"§aYour referral code: §f"+code,"§aВаш реферальный код: §f"+code)));return true;}
    @SuppressWarnings("deprecation")
    private void redeem(Player player,String raw){repository.definition(raw).thenAccept(found->player.getScheduler().execute(this,()->{if(found.isEmpty()){message(player,"§cCode was not found.","§cКод не найден.");return;}CodeDefinition definition=found.get();boolean permission=definition.requiredPermission().isBlank()||player.hasPermission(definition.requiredPermission());long playtime=Math.max(0,player.getStatistic(Statistic.PLAY_ONE_MINUTE)/20L);repository.redeem(raw,player.getUniqueId(),player.getName(),identity(player),permission,playtime).thenAccept(result->respond(player,()->{if(result.status()!=RedemptionResult.Status.ACCEPTED){message(player,"§cCode was not redeemed: §f"+status(result.status()),"§cКод не применён: §f"+status(result.status()));return;}deliver(result.transactionId(),player);}));},null,1L));}
    private void retryPending(){repository.pending().thenAccept(rewards->rewards.forEach(reward->deliver(reward.tx(),null)));}
    private void deliver(UUID tx,CommandSender requester){repository.claim(tx).thenAccept(found->sync(()->{if(found.isEmpty()){if(requester!=null)respond(requester,()->message(requester,"§cTransaction is not pending.","§cТранзакция не ожидает выдачи."));return;}CodeRepository.PendingReward reward=found.get();String owner=reward.owner()==null?"":Optional.ofNullable(Bukkit.getOfflinePlayer(reward.owner()).getName()).orElse("");reward.playerCommands().forEach(command->dispatch(command,reward.playerName(),owner));if(!owner.isBlank())reward.ownerCommands().forEach(command->dispatch(command,owner,reward.playerName()));repository.delivered(reward.tx()).thenAccept(ok->sync(()->{Player player=Bukkit.getPlayer(reward.player());if(player!=null)respond(player,()->message(player,ok?"§aCode redeemed successfully.":"§eRewards ran, but the journal needs review.",ok?"§aКод успешно применён.":"§eНаграды выполнены, но журнал требует проверки."));}));if(requester!=null)respond(requester,()->message(requester,"§aReward delivery started.","§aВыдача награды запущена."));}));}
    private void dispatch(String raw,String player,String other){String command=raw.replace("{player}",player).replace("{referrer}",other).replace("{redeemer}",other);Bukkit.dispatchCommand(Bukkit.getConsoleSender(),command);}
    private String identity(Player player){if(!getConfig().getBoolean("anti-abuse.identity-enabled",true)||player.getAddress()==null)return "";return hasher.hash(player.getAddress().getAddress().getHostAddress());}
    private String describe(CodeDefinition d){return "§e"+d.code()+" §7["+d.type()+"] limit="+(d.maxUses()==0?"∞":d.maxUses())+", player="+d.perPlayer()+", identity="+d.perIdentity()+", permission="+(d.requiredPermission().isBlank()?"none":d.requiredPermission())+", playtime="+d.minimumPlaytimeSeconds()+"s";}
    private String status(RedemptionResult.Status value){return switch(value){case NOT_FOUND->text("not found","не найден");case NOT_STARTED->text("not active yet","ещё не активен");case EXPIRED->text("expired or disabled","истёк или отключён");case LIMIT_REACHED->text("global limit reached","достигнут общий лимит");case ALREADY_USED->text("already used","уже использован");case IDENTITY_LIMIT->text("network limit reached","достигнут сетевой лимит");case SELF_REFERRAL->text("self-referral is forbidden","нельзя использовать свой код");case SAME_IDENTITY->text("same network as the referrer","та же сеть, что у пригласившего");case NO_PERMISSION->text("requirement not met","условие доступа не выполнено");case NOT_ENOUGH_PLAYTIME->text("not enough playtime","недостаточно игрового времени");case ACCEPTED->text("accepted","принят");};}
    private static int parse(String value,int min,int max){int parsed=Integer.parseInt(value);if(parsed<min||parsed>max)throw new IllegalArgumentException("Number outside "+min+".."+max);return parsed;}
    private boolean admin(CommandSender sender){if(sender.hasPermission("mcodes.admin"))return true;deny(sender);return false;}private void deny(CommandSender sender){message(sender,"§cYou do not have permission.","§cНедостаточно прав.");}private void usage(CommandSender sender){sender.sendMessage("§e/code redeem <code> | create <code> <global-limit> [per-player] [expires-hours] [permission|-] [starts-hours] | info/list/enable/disable/pending/retry/resolve/reload");}
    private void respond(CommandSender sender,Runnable task){if(sender instanceof Player player)player.getScheduler().execute(this,task,null,1L);else sync(task);}private void sync(Runnable task){getServer().getGlobalRegionScheduler().execute(this,task);}private String text(String en,String ru){return Text.tr(this,en,ru);}private void message(CommandSender sender,String en,String ru){sender.sendMessage(text(en,ru));}private static Throwable root(Throwable error){while(error.getCause()!=null)error=error.getCause();return error;}
    @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(command.getName().equals("code")&&args.length==1)return List.of("redeem","create","info","list","enable","disable","pending","retry","resolve","reload").stream().filter(value->value.startsWith(args[0].toLowerCase(Locale.ROOT))).toList();return List.of();}
}
