package io.github.miklires.mcodes;
import org.junit.jupiter.api.*;import java.time.Instant;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class CodeRepositoryTest {CodeRepository repo;@BeforeEach void open(){repo=new CodeRepository("jdbc:h2:mem:"+UUID.randomUUID()+";DB_CLOSE_DELAY=-1");repo.initialize().join();}@AfterEach void close(){repo.close();}
 @Test void redeemIsAtomicAndRewardIsClaimedOnce(){var d=promo("welcome",1,1,0,null,null,"",0);assertTrue(repo.create(d).join());UUID player=UUID.randomUUID();var result=repo.redeem("WELCOME",player,"Alex","identity-a",true,0).join();assertEquals(RedemptionResult.Status.ACCEPTED,result.status());assertEquals(RedemptionResult.Status.LIMIT_REACHED,repo.redeem("WELCOME",UUID.randomUUID(),"Steve","identity-b",true,0).join().status());assertEquals(1,repo.pending().join().size());assertTrue(repo.claim(result.transactionId()).join().isPresent());assertTrue(repo.claim(result.transactionId()).join().isEmpty());assertTrue(repo.delivered(result.transactionId()).join());}
 @Test void enforcesSchedulePermissionPlaytimeAndIdentity(){Instant now=Instant.now();repo.create(promo("future",0,1,1,now.plusSeconds(60),now.plusSeconds(120),"rank.vip",3600)).join();UUID player=UUID.randomUUID();assertEquals(RedemptionResult.Status.NOT_STARTED,repo.redeem("future",player,"Alex","same",false,0).join().status());repo.create(promo("active",0,1,1,null,now.plusSeconds(120),"rank.vip",3600)).join();assertEquals(RedemptionResult.Status.NO_PERMISSION,repo.redeem("active",player,"Alex","same",false,7200).join().status());assertEquals(RedemptionResult.Status.NOT_ENOUGH_PLAYTIME,repo.redeem("active",player,"Alex","same",true,10).join().status());assertEquals(RedemptionResult.Status.ACCEPTED,repo.redeem("active",player,"Alex","same",true,7200).join().status());assertEquals(RedemptionResult.Status.IDENTITY_LIMIT,repo.redeem("active",UUID.randomUUID(),"Steve","same",true,7200).join().status());}
 @Test void referralRejectsSelfAndSharedIdentity(){UUID owner=UUID.randomUUID(),player=UUID.randomUUID();repo.rememberIdentity(owner,"house").join();repo.create(new CodeDefinition("owner",CodeType.REFERRAL,owner,0,1,1,null,null,"",0,List.of(),List.of())).join();assertEquals(RedemptionResult.Status.SELF_REFERRAL,repo.redeem("owner",owner,"Owner","other",true,0).join().status());assertEquals(RedemptionResult.Status.SAME_IDENTITY,repo.redeem("owner",player,"Player","house",true,0).join().status());assertEquals(RedemptionResult.Status.ACCEPTED,repo.redeem("owner",player,"Player","unique",true,0).join().status());}
 @Test void oneNetworkCannotRedeemDifferentReferralCodes(){UUID firstOwner=UUID.randomUUID(),secondOwner=UUID.randomUUID();repo.create(new CodeDefinition("FIRST",CodeType.REFERRAL,firstOwner,0,1,1,null,null,"",0,List.of(),List.of())).join();repo.create(new CodeDefinition("SECOND",CodeType.REFERRAL,secondOwner,0,1,1,null,null,"",0,List.of(),List.of())).join();assertEquals(RedemptionResult.Status.ACCEPTED,repo.redeem("FIRST",UUID.randomUUID(),"Alex","shared-network",true,0).join().status());assertEquals(RedemptionResult.Status.IDENTITY_LIMIT,repo.redeem("SECOND",UUID.randomUUID(),"Steve","shared-network",true,0).join().status());}
 private static CodeDefinition promo(String code,int global,int player,int identity,Instant start,Instant end,String permission,long playtime){return new CodeDefinition(code,CodeType.PROMO,null,global,player,identity,start,end,permission,playtime,List.of("give {player} diamond"),List.of());}
}
